name: dreusables
description: 'DirtConnect - Exchange construction resources and work with reputable partners'

publish_to: 'none'

version: 1.0.0+22

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # firebase packages and plugins:
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4
  firebase_auth: ^6.1.2
  lottie: ^3.3.1
  google_maps_flutter: ^2.14.0
  google_maps_custom_marker: ^1.0.2
  firebase_storage: ^13.0.4
  firebase_crashlytics: ^5.0.4
  firebase_messaging: ^16.0.4
  cloud_firestore: ^6.1.0

  # router package
  go_router: ^17.0.0
  gif: ^2.3.0
  flutter_screenutil: ^5.9.3
  showcaseview: ^5.0.1

  # social auth packages
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1

  # local storage packages
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.2.2
  flutter_session_manager: ^1.0.3
  webview_flutter: ^4.13.1

  # device info utilities
  device_info_plus: ^9.1.2
  package_info_plus: ^8.0.0
  uuid: ^4.4.2
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  share_plus: ^12.0.1
  connectivity_plus: ^6.0.5

  # form and validations packages
  reusables:
    git:
      url: https://github.com/fatima-tehreem09/reusables.git
      ref: update

    # state management packages
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0

  # dependency injection package
  get_it: ^9.2.0

  dio: ^5.4.1
  http: ^1.2.0

  animate_do: ^3.3.4
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  phone_text_field: ^2.0.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  flutter_svg: ^2.2.3
  dartz: ^0.10.1
  permission_handler: ^12.0.1
  equatable: ^2.0.7
  geolocator: ^13.0.1
  image_picker: ^1.0.7
  google_places_flutter: ^2.0.9

dev_dependencies:
  build_runner: ^2.4.8
  analyzer: ^7.6.0
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.4
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/images/
    - assets/gif/
    - assets/logo.png
  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF

flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/logo.png'
  min_sdk_android: 21
  web:
    generate: true
    image_path: 'assets/logo.png'
    background_color: '#FFD700'
    theme_color: '#1A1A1A'
  windows:
    generate: true
    image_path: 'assets/logo.png'
    icon_size: 48
  macos:
    generate: true
    image_path: 'assets/logo.png'
  adaptive_icon_background: '#FFD700'
  adaptive_icon_foreground: 'assets/logo.png'
