name: dreusables
description: 'DirtConnect - Exchange construction resources and work with reputable partners'

publish_to: 'none'

version: 1.0.0+22

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  geolocator: ^13.0.1
  gif: ^2.3.0
  go_router: ^17.0.0
  google_maps_flutter: ^2.14.0
  http: ^1.2.0
  image_picker: ^1.0.7
  intl: ^0.20.0
  permission_handler: ^12.0.1
  webview_flutter: ^4.13.1

dev_dependencies:
  analyzer: ^7.6.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/images/
    - assets/fonts/
    - assets/gif/
    - assets/logo.png
  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SFPRODISPLAYBOLD.OTF
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.OTF
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF

flutter_intl:
  enabled: true

